import type { Metadata } from "next";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const childrenFont = Baloo_Bhaijaan_2({
  variable: "--family-children",
  subsets: ["latin"],
});

const parentFont = localFont({
  src: [
    {
      path: "../public/fonts/LamaSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/LamaSans-RegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/LamaSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/LamaSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/LamaSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--family-parents",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${childrenFont.variable} ${parentFont.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
